### ISSUE TITLE
Request provide struct of the sketch folder

### ISSUE THREAD

**Issue by Tech500** [s60sc/EspCrashDecoder#1]
I have zero output from espcrashdecoder; ESP32 core 2.0.11, Arduino IDE 2.1.1.

Believe I may have the wrong structure for the sketch folder.  

Is gdb included in the core; does it need manual installation?

William

**Comment by s60sc** [comment]
Copy the espcrashdecoder folder into the sketch folder to be analysed.
Gdb is core

**Comment by Tech500** [comment]
Already copied ESPCrashDecoder folder to sketch folder.  Size of ESPCrashDecoder.out is 0 KB.

Backtrace:

Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400d13ce  PS      : 0x00060830  A0      : 0x800d2b82  A1      : 0x3ffc51c0  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x00000014  A5      : 0x00000004  
A6      : 0x3ffbd5ac  A7      : 0x80000001  A8      : 0x00000000  A9      : 0x0000000a  
A10     : 0x3ffc1c60  A11     : 0x00000078  A12     : 0x0000e100  A13     : 0x00000003  
A14     : 0x00000001  A15     : 0x00000001  SAR     : 0x00000003  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000000  LBEG    : 0x40085e68  LEND    : 0x40085e73  LCOUNT  : 0xffffffff  


Backtrace: 0x400d13cb:0x3ffc51c0 0x400d2b7f:0x3ffc51f0

Output of ESPCrashDecoder.txt:

`set listsize 1
l *0x400d13ce
l *0x00000000
l *0x400d13cb
l *0x400d2b7f
q
`

William

**Comment by s60sc** [comment]
That is the interim file for gdb - see readme. It may be that the espressif path to gdb has changed, but I'm not able to check right now.

**Comment by Tech500** [comment]
ESP32 Core 2.0.11 gdb path?

C:\Users\William\AppData\Local\Arduino15\packages\esp32\tools\xtensa-esp-elf-gdb\11.2_20220823\bin\xtensa-esp32-elf-gdb.exe

**Comment by s60sc** [comment]
It is different, the bat file will need updating

**Comment by Tech500** [comment]
My apologies; user error, wrong board specified in ESPCrashDecoder.bat.   Switched board compiling to ESP32 Dev Module, left .bat file set to ESP32.  Works as advertized.  Thank you!

First board used to compile was an ESP32 Pico D4; with .bat file set to ESP32.

Feature request:  Input board type from Arduino IDE.

William

**Comment by Tech500** [comment]
ESP32 Core 2.0.11

ESP32 Pico D4; modified path in ESPCrashDecode.bat :FoundFile:

"C:\Users\William\AppData\Local\Arduino15\packages\esp32\tools\xtensa-esp-elf-gdb\11.2_20220823\bin\xtensa-esp32s2-elf-gdb.exe" "C:\Users\William\Documents\Arduino\libraries\Crash\build\esp32.esp32.pico32\Crash.ino.elf" --batch --command=%addresses% > %decoded% 2>nul 

ESPCrashDecoder.out was produced after doing this modification to the path.

**Comment by s60sc** [comment]
I'll check the paths for different board types and amend bat file

**Comment by Tech500** [comment]
Thank you s60sc!

**Comment by s60sc** [comment]
looks like different boards can have different elf folder. In new bat file change elfTarget to pico32
